### ISSUE TITLE
load data into foreign table?

### ISSUE THREAD

**Issue by inkrement** [ossc-db/pg_bulkload#23]
Is it possible to use pg_bulkload with foreign tables (e.g. cstore_fdw)? I tried it, but I got the following error message:

```
ERROR: query failed: ERROR:  cannot load to non-table relation "videos"
```

**Comment by bwtakacy** [comment]
No, because it truly depends the implementation of foreign data wrappers.

Pg_bulkload load data quickly because it specializez the PostgreSQL table format.
The data format of foreign tables are different for each.
It may be possible to enhance pg_bulkload to load data for specific foreign tables.

**Comment by amitlan** [comment]
Yeah, just like COPY supports only regular tables because it manipulates the underlying storage directly.  Other table types (like foreign tables) cannot be manipulated like that.

Closing now as it seems hard to implement that in pg_bulkload.  If you have any ideas, please feel free to re-open and discuss. :)
