### ISSUE TITLE
Pg_bulkload column different order

### ISSUE THREAD

**Issue by rajmhnr** [ossc-db/pg_bulkload#38]
Hi,

I have a source file with following order without header.

COLA;COLB;COLC
1;2;3

Table column order:

COLB
COLA
COLC

Here COLA should be mapped to COLA, COLB should be mapped to COLB and COLC should be mapped to COLC.

This case can be accomplished without FILTER option? Why because, we are not defining anywhere, which column to load.

Thanks

**Comment by amitlan** [comment]
You'd need to use FILTER here to implement the mapping logic.

pg_bulkload determines columns to load by looking up the schema of the target table in the system catalog.  If you specify values in the source file in some different order, then you might get an error if the input string value of some field is not convertible to the type of the corresponding column of the table.  So be careful if you don't want wrong fields to be loaded into the table's columns, because pg_bulkload won't complain if there is no mismatch of types - it will silently load the data as long as a field's string value can be coerced to the target column type.

@bwtakacy, do you know of any way beside using FILTER?

**Comment by bwtakacy** [comment]
> do you know of any way beside using FILTER?
Sorry, don't.

This is just the reason of FILTER feature exists.

**Comment by amitlan** [comment]
So, I guess @rajmhnr is happy doing this using a FILTER function.  Closing.
