### ISSUE TITLE
pg_bulkload supports the Postgres Enterprise Edition(EDB)?

### ISSUE THREAD

**Issue by rajmhnr** [ossc-db/pg_bulkload#48]
Will the pg_bulkload supports the Postgres Enterprise Edition(EDB)? I want to try that in EDB.

Thanks

**Comment by bwtakacy** [comment]
We do not plan to supports EDB.

There is the EDB's custom data loading tool, EDG*Loader and this is similar to pg_bulkload because it can use the direct path insert loading.

Please see the EDB documentations and so one about that.

https://www.enterprisedb.com/docs/en/9.4/oracompat/Database_Compatibility_for_Oracle_Developers_Guide.1.291.html

**Comment by rajmhnr** [comment]
Yes. We have used that.But it has few drawbacks. If any record fails, entire session records were rolled back.
Thanks

**Comment by amitlan** [comment]
As bwtakacy pointed out, pg_bulkload is supported to work with community Postgres.  Since EDB's Postgres is derived from community Postgres, pg_bulkload should work with it if the former provides all the needed interfaces.  I have not checked if that's true though.

With the limited resources that we have, it's not possible to commit to supporting pg_bulkload with commercial derivatives of Postgres, if it needs us to make changes in pg_bulkload.

Closing this.  Feel free to comment if you wanted to ask more questions.
