### ISSUE TITLE
function generate_series(integer,integer) is not unique?

### ISSUE THREAD

**Issue by LoveTommy** [ossc-db/pg_bulkload#52]
type = function
input = generate_series(1,1000) 
error: function generate_series(integer, integer) is not unique

**Comment by amitlan** [comment]
I think "function is not unique" seems like a bug that can be fixed.

Even after fixing that, you still cannot use generate_series(int, int) as input.  pg_bulkload expects the function to return SET OF "table records".  So, if you have the following table:

```
CREATE TABLE foo (a int);
```

and you want to insert numbers 1..1000 into it, you will have to write a wrapper function around generate_series(integer, integer) so that pg_bulkload's above-mentioned requirement is satisfied:

```
CREATE_FUNCTION foo_loader(int, int) RETURNS SETOF foo AS
  AS $$ SELECT generate_series($1, $2); $$
  LANGUAGE SQL;
```
